//
//  CreateOrderWorker.swift
//  CleanStore
//
//  Created by Jordan Anderson on 3/17/19.
//  Copyright (c) 2019 Dub Labs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CreateOrderWorker
{
  func doSomeWork()
  {
  }
}
